# Generated by Django 5.1.15 on 2026-07-16 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sshsession',
            name='env_script',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
