# Generated by Django 5.1.15 on 2026-07-28 07:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0003_grantrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='EngUserRights',
            fields=[
                ('user_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('user_password', models.CharField(max_length=255)),
                ('user_created', models.DateField(default=datetime.date.today)),
            ],
            options={
                'db_table': 'eng_user_rights',
            },
        ),
        migrations.CreateModel(
            name='EngUserRightsDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=30)),
                ('env_scr', models.CharField(max_length=30)),
                ('db_name', models.CharField(max_length=30)),
                ('user_created', models.DateField(default=datetime.date.today)),
            ],
            options={
                'db_table': 'eng_user_rights_detail',
                'constraints': [models.UniqueConstraint(fields=('user_id', 'env_scr', 'db_name'), name='pk_urd')],
            },
        ),
    ]
