# Generated by Django 5.1.15 on 2026-10-01 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0004_enguserrights_enguserrightsdetail'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GrantRequest',
        ),
    ]
